# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\",\n\x0cImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\r\n\x05\x65vent\x18\x02 \x01(\t\"O\n\x13UploadImageResponse\x12\x13\n\x0bimage_event\x18\x01 \x01(\t\x12\x11\n\timage_url\x18\x02 \x01(\t\x12\x10\n\x08image_id\x18\x03 \x01(\t\"2\n\x0bPredictItem\x12\x11\n\timage_url\x18\x01 \x01(\t\x12\x10\n\x08image_id\x18\x02 \x01(\t\";\n\x14PredictImageResponse\x12#\n\rpredict_items\x18\x01 \x03(\x0b\x32\x0c.PredictItem2x\n\x0cImageService\x12\x32\n\x0bUploadImage\x12\r.ImageRequest\x1a\x14.UploadImageResponse\x12\x34\n\x0cPredictImage\x12\r.ImageRequest\x1a\x15.PredictImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=17
  _globals['_IMAGEREQUEST']._serialized_end=61
  _globals['_UPLOADIMAGERESPONSE']._serialized_start=63
  _globals['_UPLOADIMAGERESPONSE']._serialized_end=142
  _globals['_PREDICTITEM']._serialized_start=144
  _globals['_PREDICTITEM']._serialized_end=194
  _globals['_PREDICTIMAGERESPONSE']._serialized_start=196
  _globals['_PREDICTIMAGERESPONSE']._serialized_end=255
  _globals['_IMAGESERVICE']._serialized_start=257
  _globals['_IMAGESERVICE']._serialized_end=377
# @@protoc_insertion_point(module_scope)
